/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Body struct {
	// Define which fields need to be returned. Default value is ALL
	Fields []string `json:"fields,omitempty"`
	Things []Thing  `json:"things,omitempty"`
}
