/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// This meta field contains additional info about the classified reference property
type ReferenceMetaClassification struct {
	// Mean distance of all neighbors from the winning group
	WinningDistance float32 `json:"winningDistance,omitempty"`
	// Mean distance of all neighbors from the losing group. Optional. If k equals the size of the winning group, there is no losing group.
	LosingDistance float32 `json:"losingDistance,omitempty"`
}
