/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Principal struct {
	// The username that was extracted either from the authentication information
	Username string   `json:"username,omitempty"`
	Groups   []string `json:"groups,omitempty"`
}
