/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// GraphQL based response: http://facebook.github.io/graphql/.
type GraphQlResponse struct {
	// GraphQL data object.
	Data map[string]JsonObject `json:"data,omitempty"`
	// Array with errors.
	Errors []GraphQlError `json:"errors,omitempty"`
}
