/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// GraphQL query based on: http://facebook.github.io/graphql/.
type GraphQlQuery struct {
	// The name of the operation if multiple exist in the query.
	OperationName string `json:"operationName,omitempty"`
	// Query based on GraphQL syntax.
	Query string `json:"query,omitempty"`
	// Additional variables for the query.
	Variables *interface{} `json:"variables,omitempty"`
}
