/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PhoneNumber struct {
	// The raw input as the phone number is present in your raw data set. It will be parsed into the standardized formats if valid.
	Input string `json:"input,omitempty"`
	// Read-only. Parsed result in the international format (e.g. +49 123 ...)
	InternationalFormatted string `json:"internationalFormatted,omitempty"`
	// Optional. The ISO 3166-1 alpha-2 country code. This is used to figure out the correct countryCode and international format if only a national number (e.g. 0123 4567) is provided
	DefaultCountry string `json:"defaultCountry,omitempty"`
	// Read-only. The numerical country code (e.g. 49)
	CountryCode float32 `json:"countryCode,omitempty"`
	// Read-only. The numerical representation of the national part
	National float32 `json:"national,omitempty"`
	// Read-only. Parsed result in the national format (e.g. 0123 456789)
	NationalFormatted string `json:"nationalFormatted,omitempty"`
	// Read-only. Indicates whether the parsed number is a valid phone number
	Valid bool `json:"valid,omitempty"`
}
