/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Definitions of semantic schemas (also see: https://github.com/semi-technologies/weaviate-semantic-schemas).
type Schema struct {
	// Semantic classes that are available.
	Classes []Class `json:"classes,omitempty"`
	// Email of the maintainer.
	Maintainer string `json:"maintainer,omitempty"`
	// Name of the schema.
	Name string `json:"name,omitempty"`
	// Type of schema, should be \"thing\" or \"action\".
	Type_ string `json:"type,omitempty"`
}
