/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// This underscore property contains additional info about the how the class was vectorized
type Interpretation struct {
	// The input that was used to vectorize this object
	Source []InterpretationSource `json:"source,omitempty"`
}
