/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Either set beacon (direct reference) or set class and schema (concept reference)
type SingleRef struct {
	// If using a concept reference (rather than a direct reference), specify the desired class name here
	Class string `json:"class,omitempty"`
	// If using a concept reference (rather than a direct reference), specify the desired properties here
	Schema *PropertySchema `json:"schema,omitempty"`
	// If using a direct reference, specify the URI to point to the cross-ref here. Should be in the form of weaviate://localhost/things/<uuid> for the example of a local cross-ref to a thing
	Beacon string `json:"beacon,omitempty"`
	// If using a direct reference, this read-only fields provides a link to the refernced resource. If 'origin' is globally configured, an absolute URI is shown - a relative URI otherwise.
	Href string `json:"href,omitempty"`
	// Additional Meta information about this particular reference. Only shown if meta==true.
	Meta *ReferenceMeta `json:"meta,omitempty"`
	// Additional Meta information about classifications if the item was part of one
	Classification *ReferenceMetaClassification `json:"_classification,omitempty"`
}
