/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GraphQlErrorLocations struct {
	Column int64 `json:"column,omitempty"`
	Line int64 `json:"line,omitempty"`
}
