/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Additional Meta information about this particular reference.
type ReferenceMeta struct {
	// If a property was set through a classification, this meta field contains additional info
	Classification *ReferenceMetaClassification `json:"classification,omitempty"`
}
