/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Additional Meta information about a single thing/action object.
type UnderscoreProperties struct {
	// If this object was subject of a classificiation, additional meta info about this classification is available here
	Classification *UnderscorePropertiesClassification `json:"classification,omitempty"`
	// This object's position in the Contextionary vector space
	Vector *C11yVector `json:"vector,omitempty"`
	// Additional information about how the object was vectorized
	Interpretation *Interpretation `json:"interpretation,omitempty"`
	// Neighboring concepts of your search results
	NearestNeighbors *NearestNeighbors `json:"nearestNeighbors,omitempty"`
	// The concepts vector projected into a lower dimensional space (for visualization purposes)
	FeatureProjection *FeatureProjection `json:"featureProjection,omitempty"`
	// The semantic path between the search query and the result. Only on 'explore' searches
	SemanticPath *SemanticPath `json:"semanticPath,omitempty"`
}
