/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// An error response caused by a GraphQL query.
type GraphQlError struct {
	Locations []GraphQlErrorLocations `json:"locations,omitempty"`
	Message   string                  `json:"message,omitempty"`
	Path      []string                `json:"path,omitempty"`
}
