/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// An error response given by Weaviate end-points.
type ErrorResponse struct {
	Error_ []ErrorResponseError `json:"error,omitempty"`
}
