/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// Additional information to a specific classification
type ClassificationMeta struct {
	// time when this classification was started
	Started time.Time `json:"started,omitempty"`
	// time when this classification finished
	Completed time.Time `json:"completed,omitempty"`
	// number of objects which were taken into consideration for classification
	Count int32 `json:"count,omitempty"`
	// number of objects successfully classified
	CountSucceeded int32 `json:"countSucceeded,omitempty"`
	// number of objects which could not be classified - see error message for details
	CountFailed int32 `json:"countFailed,omitempty"`
}
