/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Property struct {
	// Can be a reference to another type when it starts with a capital (for example Person), otherwise \"string\" or \"int\".
	DataType []string `json:"dataType,omitempty"`
	// DEPRECATED - do not use anymore.
	Cardinality string `json:"cardinality,omitempty"`
	// Description of the property.
	Description string `json:"description,omitempty"`
	// Set this to true if the object vector should include this property's name in calculating the overall vector position. If set to false (default), only the property value will be used.
	VectorizePropertyName bool `json:"vectorizePropertyName,omitempty"`
	// Name of the property as URI relative to the schema URL.
	Name string        `json:"name,omitempty"`
	Keywords *Keywords `json:"keywords,omitempty"`
	// Optional. By default each property is fully indexed both for full-text, as well as vector-search. You can ignore properties in searches by explicitly setting index to false. Not set is the same as true
	Index bool `json:"index,omitempty"`
}
