/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Filter search results using a where filter
type WhereFilter struct {
	// combine multiple where filters, requires 'And' or 'Or' operator
	Operands []WhereFilter `json:"operands,omitempty"`
	// operator to use
	Operator string `json:"operator,omitempty"`
	// path to the property currently being filtered
	Path []string `json:"path,omitempty"`
	// value as integer
	ValueInt int64 `json:"valueInt,omitempty"`
	// value as number/float
	ValueNumber float32 `json:"valueNumber,omitempty"`
	// value as boolean
	ValueBoolean bool `json:"valueBoolean,omitempty"`
	// value as string
	ValueString string `json:"valueString,omitempty"`
	// value as text (on text props)
	ValueText string `json:"valueText,omitempty"`
	// value as date (as string)
	ValueDate string `json:"valueDate,omitempty"`
	// value as geo coordinates and distance
	ValueGeoRange *WhereFilterGeoRange `json:"valueGeoRange,omitempty"`
}
