/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Either a JSONPatch document as defined by RFC 6902 (from, op, path, value), or a merge document (RFC 7396).
type PatchDocumentThing struct {
	// A string containing a JSON Pointer value.
	From string `json:"from,omitempty"`
	// The operation to be performed.
	Op string `json:"op"`
	// A JSON-Pointer.
	Path string `json:"path"`
	// The value to be used within the operations.
	Value *interface{} `json:"value,omitempty"`
	Merge *Thing       `json:"merge,omitempty"`
}
