/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A group of neighboring concepts
type NearestNeighbor struct {
	// The neighboring concept
	Concept string `json:"concept,omitempty"`
	// The distance between the result and this neighbor
	Distance float32 `json:"distance,omitempty"`
	// The neighbor's vector position
	Vector []float32 `json:"vector,omitempty"`
}
