/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type C11yVectorBasedQuestionInnerClassProps struct {
	PropsVectors []float32 `json:"propsVectors,omitempty"`
	// String with valuename.
	Value string `json:"value,omitempty"`
}
