/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Weighted results for all words
type C11yWordsResponseConcatenatedWord struct {
	ConcatenatedWord             string                `json:"concatenatedWord,omitempty"`
	SingleWords                  []interface{}         `json:"singleWords,omitempty"`
	ConcatenatedVector           *C11yVector           `json:"concatenatedVector,omitempty"`
	ConcatenatedNearestNeighbors *C11yNearestNeighbors `json:"concatenatedNearestNeighbors,omitempty"`
}
