/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// This underscore property contains additional info about the classification which affected this object
type UnderscorePropertiesClassification struct {
	// unique identifier of the classification run
	Id string `json:"id,omitempty"`
	// Timestamp when this particular object was classified. This is usually sooner than the overall completion time of the classification, as the overall completion time will only be set once every object has been classified.
	Completed time.Time `json:"completed,omitempty"`
	// The properties in scope of the classification. Note that this doesn't mean that these fields were necessarily classified, this only means that those fields were in scope of the classificiation. See \"classifiedFields\" for details.
	Scope []string `json:"scope,omitempty"`
	// The (reference) fields which were classified as part of this classification. Note that this might contain fewere entries than \"scope\", if one of the fields was already set prior to the classification, for example
	ClassifiedFields []string `json:"classifiedFields,omitempty"`
	// The (primitive) field(s) which were used as a basis for classification. For example, if the type of classification is \"knn\" with k=3, the 3 nearest neighbors - based on these fields - were considered for the classification.
	BasedOn []string `json:"basedOn,omitempty"`
}
