/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A semantic path between two objects, e.g. a search query and a result
type SemanticPath struct {
	Path []SemanticPathElement `json:"path,omitempty"`
}
