/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Link struct {
	// target of the link
	Href string `json:"href,omitempty"`
	// relationship if both resources are related, e.g. 'next', 'previous', 'parent', etc.
	Rel string `json:"rel,omitempty"`
	// human readable name of the resource group
	Name string `json:"name,omitempty"`
	// weaviate documentation about this resource group
	DocumentationHref string `json:"documentationHref,omitempty"`
}
