/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A single peer in the network.
type PeerUpdate struct {
	// The session ID of the peer.
	Id string `json:"id,omitempty"`
	// Human readable name.
	Name string `json:"name,omitempty"`
	// The location where the peer is exposed to the internet.
	Uri string `json:"uri,omitempty"`
	// The latest known hash of the peer's schema.
	SchemaHash string `json:"schemaHash,omitempty"`
}
