/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type Deprecation struct {
	// The id that uniquely identifies this particular deprecations (mostly used internally)
	Id string `json:"id,omitempty"`
	// Whether the problematic API functionality is deprecated (planned to be removed) or already removed
	Status string `json:"status,omitempty"`
	// Describes which API is effected, usually one of: REST, GraphQL
	ApiType string `json:"apiType,omitempty"`
	// What this deprecation is about
	Msg string `json:"msg,omitempty"`
	// User-required action to not be affected by the (planned) removal
	Mitigation string `json:"mitigation,omitempty"`
	// The deprecation was introduced in this version
	SinceVersion string `json:"sinceVersion,omitempty"`
	// A best-effort guess of which upcoming version will remove the feature entirely
	PlannedRemovalVersion string `json:"plannedRemovalVersion,omitempty"`
	// If the feature has already been removed, it was removed in this version
	RemovedIn string `json:"removedIn,omitempty"`
	// If the feature has already been removed, it was removed at this timestamp
	RemovedTime time.Time `json:"removedTime,omitempty"`
	// The deprecation was introduced in this version
	SinceTime time.Time `json:"sinceTime,omitempty"`
	// The locations within the specified API affected by this deprecation
	Locations []string `json:"locations,omitempty"`
}
