/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Contains meta information of the current Weaviate instance.
type Meta struct {
	// The url of the host.
	Hostname string `json:"hostname,omitempty"`
	// Version of weaviate you are currently running
	Version string `json:"version,omitempty"`
	// Number of total words in the contextionary
	ContextionaryWordCount float32 `json:"contextionaryWordCount,omitempty"`
	// Version of the contextionary service connected to weaviate
	ContextionaryVersion string `json:"contextionaryVersion,omitempty"`
}
