/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Class struct {
	// Name of the class as URI relative to the schema URL.
	Class string       `json:"class,omitempty"`
	Keywords *Keywords `json:"keywords,omitempty"`
	// Set this to true if the object vector should include the class name in calculating the overall vector position
	VectorizeClassName bool `json:"vectorizeClassName,omitempty"`
	// Description of the class.
	Description string `json:"description,omitempty"`
	// The properties of the class.
	Properties []Property `json:"properties,omitempty"`
}
