/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GeoCoordinates struct {
	// The latitude of the point on earth in decimal form
	Latitude float32 `json:"latitude,omitempty"`
	// The longitude of the point on earth in decimal form
	Longitude float32 `json:"longitude,omitempty"`
}
