/*
 * Weaviate
 *
 * Open Source Search Graph (GraphQL/RESTful/P2P)
 *
 * API version: 0.22.17
 * Contact: hello@semi.technology
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A group of neighboring concepts
type NearestNeighbors struct {
	// The individual neighbor items
	Neighbors []NearestNeighbor `json:"neighbors,omitempty"`
}
