// Code generated by go-swagger; DO NOT EDIT.

package rest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/weaviate/weaviate-go-client/v6/weaviate/internal/clients/rest/rest/authz"
	"github.com/weaviate/weaviate-go-client/v6/weaviate/internal/clients/rest/rest/backups"
	"github.com/weaviate/weaviate-go-client/v6/weaviate/internal/clients/rest/rest/batch"
	"github.com/weaviate/weaviate-go-client/v6/weaviate/internal/clients/rest/rest/classifications"
	"github.com/weaviate/weaviate-go-client/v6/weaviate/internal/clients/rest/rest/cluster"
	"github.com/weaviate/weaviate-go-client/v6/weaviate/internal/clients/rest/rest/distributed_tasks"
	"github.com/weaviate/weaviate-go-client/v6/weaviate/internal/clients/rest/rest/graphql"
	"github.com/weaviate/weaviate-go-client/v6/weaviate/internal/clients/rest/rest/meta"
	"github.com/weaviate/weaviate-go-client/v6/weaviate/internal/clients/rest/rest/nodes"
	"github.com/weaviate/weaviate-go-client/v6/weaviate/internal/clients/rest/rest/objects"
	"github.com/weaviate/weaviate-go-client/v6/weaviate/internal/clients/rest/rest/operations"
	"github.com/weaviate/weaviate-go-client/v6/weaviate/internal/clients/rest/rest/replication"
	"github.com/weaviate/weaviate-go-client/v6/weaviate/internal/clients/rest/rest/schema"
	"github.com/weaviate/weaviate-go-client/v6/weaviate/internal/clients/rest/rest/users"
	"github.com/weaviate/weaviate-go-client/v6/weaviate/internal/clients/rest/rest/well_known"
)

// Default weaviate HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/v1"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new weaviate HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Weaviate {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new weaviate HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Weaviate {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new weaviate client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Weaviate {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(Weaviate)
	cli.Transport = transport
	cli.Authz = authz.New(transport, formats)
	cli.Backups = backups.New(transport, formats)
	cli.Batch = batch.New(transport, formats)
	cli.Classifications = classifications.New(transport, formats)
	cli.Cluster = cluster.New(transport, formats)
	cli.DistributedTasks = distributed_tasks.New(transport, formats)
	cli.Graphql = graphql.New(transport, formats)
	cli.Meta = meta.New(transport, formats)
	cli.Nodes = nodes.New(transport, formats)
	cli.Objects = objects.New(transport, formats)
	cli.Operations = operations.New(transport, formats)
	cli.Replication = replication.New(transport, formats)
	cli.Schema = schema.New(transport, formats)
	cli.Users = users.New(transport, formats)
	cli.WellKnown = well_known.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Weaviate is a client for weaviate
type Weaviate struct {
	Authz authz.ClientService

	Backups backups.ClientService

	Batch batch.ClientService

	Classifications classifications.ClientService

	Cluster cluster.ClientService

	DistributedTasks distributed_tasks.ClientService

	Graphql graphql.ClientService

	Meta meta.ClientService

	Nodes nodes.ClientService

	Objects objects.ClientService

	Operations operations.ClientService

	Replication replication.ClientService

	Schema schema.ClientService

	Users users.ClientService

	WellKnown well_known.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Weaviate) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Authz.SetTransport(transport)
	c.Backups.SetTransport(transport)
	c.Batch.SetTransport(transport)
	c.Classifications.SetTransport(transport)
	c.Cluster.SetTransport(transport)
	c.DistributedTasks.SetTransport(transport)
	c.Graphql.SetTransport(transport)
	c.Meta.SetTransport(transport)
	c.Nodes.SetTransport(transport)
	c.Objects.SetTransport(transport)
	c.Operations.SetTransport(transport)
	c.Replication.SetTransport(transport)
	c.Schema.SetTransport(transport)
	c.Users.SetTransport(transport)
	c.WellKnown.SetTransport(transport)
}
