package data

import (
	"context"
	"errors"
	"fmt"
	"slices"
	"time"

	"github.com/google/uuid"
	"github.com/weaviate/weaviate-go-client/v6/internal"
	"github.com/weaviate/weaviate-go-client/v6/internal/api"
	"github.com/weaviate/weaviate-go-client/v6/internal/dev"
	"github.com/weaviate/weaviate-go-client/v6/types"
)

func NewClient(t internal.Transport, rd api.RequestDefaults) *Client {
	dev.AssertNotNil(t, "transport")

	return &Client{
		transport: t,
		defaults:  rd,
	}
}

type Client struct {
	transport internal.Transport
	defaults  api.RequestDefaults
}

type (
	Reference  api.ObjectReference
	References map[string][]Reference
)

type Object struct {
	UUID          *uuid.UUID
	CreatedAt     time.Time
	LastUpdatedAt time.Time
	Properties    map[string]any
	References    References
	Vectors       []types.Vector
}

type InsertResult struct {
	Took   time.Duration
	Errors map[uuid.UUID]string
}

// Insert new objects into the collection.
//
// To create objects without data or vectors and a UUID
// generated by the server, pass nils as the second parameter.
func (c *Client) Insert(ctx context.Context, objects ...*Object) (*InsertResult, error) {
	batch := slices.Grow([]api.BatchObject(nil), len(objects))
	for _, o := range objects {
		if o == nil {
			o = new(Object)
		}

		var id uuid.UUID
		if o.UUID != nil {
			id = *o.UUID
		} else {
			id = uuid.New()
		}
		batch = append(batch, api.BatchObject{
			UUID:       id,
			Properties: o.Properties,
			Vectors:    apiVectors(o.Vectors),
			References: apiReferences(o.References),
		})
	}

	req := &api.InsertObjectBatchRequest{
		RequestDefaults: c.defaults,
		Objects:         batch,
	}

	var resp api.InsertObjectBatchResponse
	if err := c.transport.Do(ctx, req, &resp); err != nil {
		return nil, fmt.Errorf("insert objects: %w", err)
	}

	dev.Assert(len(resp.Positions) == len(resp.Errors), "indices and errors not aligned")

	r := &InsertResult{
		Took:   resp.Took,
		Errors: internal.MakeMap[uuid.UUID, string](len(resp.Positions)),
	}

	for i, pos := range resp.Positions {
		r.Errors[batch[pos].UUID] = resp.Errors[i]
	}

	return r, nil
}

// Replace object in the collection. The [Object.UUID] must be non-nil,
// but can be a [uuid.Nil] if that is the object's ID in the database.
func (c *Client) Replace(ctx context.Context, o Object) error {
	if o.UUID == nil {
		return errors.New("uuid is nil")
	}

	req := &api.ReplaceObjectRequest{
		RequestDefaults: c.defaults,
		UUID:            o.UUID,
		Properties:      o.Properties,
		Vectors:         apiVectors(o.Vectors),
		References:      apiReferences(o.References),
	}

	if err := c.transport.Do(ctx, req, nil); err != nil {
		return fmt.Errorf("replace object: %w", err)
	}

	return nil
}

// Dlete an object from the collection.
func (c *Client) Delete(ctx context.Context, id uuid.UUID) error {
	req := api.DeleteObjectRequest{
		RequestDefaults: c.defaults,
		UUID:            id,
	}
	if err := c.transport.Do(ctx, &req, nil); err != nil {
		return fmt.Errorf("delete object: %w", err)
	}
	return nil
}

func apiVectors(vectors []types.Vector) []api.Vector {
	if len(vectors) == 0 {
		return nil
	}

	vs := make([]api.Vector, len(vectors))
	for i, v := range vectors {
		vs[i] = api.Vector(v)
	}
	return vs
}

func apiReferences(rs References) api.ObjectReferences {
	if len(rs) == 0 {
		return nil
	}

	out := make(api.ObjectReferences, len(rs))
	for name, r := range rs {
		refs := make([]api.ObjectReference, len(r))
		for i := range r {
			refs[i] = api.ObjectReference(r[i])
		}
		out[name] = refs
	}
	return out
}
