package data

import (
	"context"
	"errors"
	"fmt"
	"slices"
	"time"

	"github.com/google/uuid"
	"github.com/weaviate/weaviate-go-client/v6/internal"
	"github.com/weaviate/weaviate-go-client/v6/internal/api"
	"github.com/weaviate/weaviate-go-client/v6/internal/dev"
	"github.com/weaviate/weaviate-go-client/v6/query/filter"
	"github.com/weaviate/weaviate-go-client/v6/types"
)

func NewClient(t internal.Transport, rd api.RequestDefaults) *Client {
	dev.AssertNotNil(t, "transport")

	return &Client{
		transport: t,
		defaults:  rd,
	}
}

type Client struct {
	transport internal.Transport
	defaults  api.RequestDefaults
}

type (
	ObjectPath api.ObjectPath
	Reference  struct {
		// Origin of the reference. Required when creating references
		// via [Client.AddReferences].
		Origin ObjectPath
		// Name of the referenced collection. Required for multi-target references.
		Collection string
		// ID of the referenced object.
		UUID uuid.UUID
	}
	References map[string][]Reference
)

type Object struct {
	UUID          *uuid.UUID
	CreatedAt     time.Time
	LastUpdatedAt time.Time
	Properties    map[string]any
	References    References
	Vectors       []types.Vector
}

type InsertResult struct {
	Took time.Duration
}

type InsertError struct {
	Errors map[uuid.UUID]string
}

func (ie InsertError) Error() string {
	return fmt.Sprintf("insert failed for %d objects", len(ie.Errors))
}

// Insert new objects into the collection.
//
// To create objects without data or vectors and a UUID
// generated by the server, pass nils as the second parameter.
func (c *Client) Insert(ctx context.Context, objects ...*Object) (*InsertResult, error) {
	batch := slices.Grow([]api.BatchObject(nil), len(objects))
	for _, o := range objects {
		batch = append(batch, o.ToAPI())
	}

	req := &api.InsertObjectsRequest{
		RequestDefaults: c.defaults,
		Objects:         batch,
	}

	var resp api.InsertObjectsResponse
	if err := c.transport.Do(ctx, req, &resp); err != nil {
		return nil, fmt.Errorf("insert objects: %w", err)
	}

	r := &InsertResult{Took: resp.Took}
	if len(resp.Errors) == 0 {
		return r, nil
	}

	dev.Assert(len(resp.Positions) == len(resp.Errors), "indices and errors not aligned")
	err := InsertError{
		Errors: internal.MakeMap[uuid.UUID, string](len(resp.Positions)),
	}
	for i, pos := range resp.Positions {
		err.Errors[batch[pos].UUID] = resp.Errors[i]
	}

	return r, err
}

// Replace object in the collection. The [Object.UUID] must be non-nil,
// but can be a [uuid.Nil] if that is the object's ID in the database.
func (c *Client) Replace(ctx context.Context, o Object) error {
	if o.UUID == nil {
		return errors.New("uuid is nil")
	}

	req := &api.ReplaceObjectRequest{
		RequestDefaults: c.defaults,
		UUID:            o.UUID,
		Properties:      o.Properties,
		Vectors:         apiVectors(o.Vectors),
		References:      apiReferences(o.References),
	}

	if err := c.transport.Do(ctx, req, nil); err != nil {
		return fmt.Errorf("replace object: %w", err)
	}

	return nil
}

// Delete an object from the collection.
func (c *Client) Delete(ctx context.Context, id uuid.UUID) error {
	req := api.DeleteObjectRequest{
		RequestDefaults: c.defaults,
		UUID:            id,
	}
	if err := c.transport.Do(ctx, &req, nil); err != nil {
		return fmt.Errorf("delete object: %w", err)
	}
	return nil
}

type AddReferencesResult struct {
	Took   time.Duration
	Errors map[Reference]string
}

func (c *Client) AddReferences(ctx context.Context, references ...Reference) (*AddReferencesResult, error) {
	batch := slices.Grow([]api.Reference(nil), len(references))

	for _, ref := range references {
		batch = append(batch, ref.ToAPI())
	}

	req := &api.InsertReferencesRequest{
		RequestDefaults: c.defaults,
		References:      batch,
	}

	var resp api.InsertReferencesResponse
	if err := c.transport.Do(ctx, req, &resp); err != nil {
		return nil, fmt.Errorf("add references: %w", err)
	}

	dev.Assert(len(resp.Positions) == len(resp.Errors), "indices and errors not aligned")

	r := &AddReferencesResult{
		Took:   resp.Took,
		Errors: internal.MakeMap[Reference, string](len(resp.Positions)),
	}

	for i, pos := range resp.Positions {
		r.Errors[references[pos]] = resp.Errors[i]
	}

	return r, nil
}

type DeleteSelected struct {
	// Filter selects objects which will be deleted.
	Filter filter.Expr

	// DryRun reports UUIDs that matched the filter
	// without deleting the objects.
	DryRun bool

	Verbose bool
}

type DeleteSelectedResult api.DeleteObjectsResponse

func (c *Client) DeleteSelected(ctx context.Context, options DeleteSelected) (*DeleteSelectedResult, error) {
	req := &api.DeleteObjectsRequest{
		RequestDefaults: c.defaults,
		DryRun:          options.DryRun,
		Verbose:         options.Verbose,
	}

	if options.Filter != nil {
		if expr := options.Filter.Expr(); expr != nil {
			req.Filter = *expr
		}
	}

	var resp api.DeleteObjectsResponse
	if err := c.transport.Do(ctx, req, &resp); err != nil {
		return nil, fmt.Errorf("delete selected objects: %w", err)
	}

	return (*DeleteSelectedResult)(&resp), nil
}

func apiVectors(vectors []types.Vector) []api.Vector {
	if len(vectors) == 0 {
		return nil
	}

	vs := make([]api.Vector, len(vectors))
	for i, v := range vectors {
		vs[i] = api.Vector(v)
	}
	return vs
}

func apiReferences(rs References) api.References {
	out := internal.MakeMap[string, []api.Reference](len(rs))
	for name, references := range rs {
		refs := slices.Grow([]api.Reference(nil), len(references))
		for i := range references {
			refs = append(refs, api.Reference{
				Origin: api.ObjectPath(references[i].Origin),
				Target: api.ObjectPath{
					Collection: references[i].Collection,
					UUID:       references[i].UUID,
				},
			})
		}
		out[name] = refs
	}
	return out
}

func (o *Object) ToAPI() api.BatchObject {
	if o == nil {
		return api.BatchObject{UUID: uuid.New()}
	}

	var id uuid.UUID
	if o.UUID != nil {
		id = *o.UUID
	} else {
		id = uuid.New()
	}

	return api.BatchObject{
		UUID:       id,
		Properties: o.Properties,
		Vectors:    apiVectors(o.Vectors),
		References: apiReferences(o.References),
	}
}

func (ref *Reference) ToAPI() api.Reference {
	return api.Reference{
		Origin: api.ObjectPath(ref.Origin),
		Target: api.ObjectPath{
			Collection: ref.Collection,
			UUID:       ref.UUID,
		},
	}
}
