name: golangci-lint

on:
  push:
    branches:
      - main
    tags:
      - "**"
    paths-ignore:
      - readme.md
      - license.md
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.9.0
          args: --timeout=3m
          working-directory: weaviate/
