on:
  workflow_call:

env:
  WEAVIATE_VERSION: 1.32.0

jobs:
  auth-tests:
    name: Auth integration tests
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      OKTA_CLIENT_SECRET: ${{ secrets.OKTA_CLIENT_SECRET }}
      WCS_DUMMY_CI_PW: ${{ secrets.WCS_DUMMY_CI_PW }}
      OKTA_DUMMY_CI_PW: ${{ secrets.OKTA_DUMMY_CI_PW }}
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: ${{ !github.event.pull_request.head.repo.fork }}
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'
          cache: true
      - name: Run tests
        run: WEAVIATE_VERSION=${WEAVIATE_VERSION} ./tools/run_tests.sh --auth-integration-only
  tests:
    name: Integration
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        auth_integration: [ "auth_enabled", "auth_disabled" ]
    env:
      EXTERNAL_WEAVIATE_RUNNING: false
      OKTA_DUMMY_CI_PW: ${{ secrets.OKTA_DUMMY_CI_PW }}
      INTEGRATION_TESTS_AUTH: ${{ matrix.auth_integration }}
      OPENAI_APIKEY: ${{ secrets.OPENAI_APIKEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: ${{ !github.event.pull_request.head.repo.fork }}
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'
          cache: true
      - name: Run tests
        run: WEAVIATE_VERSION=${WEAVIATE_VERSION} ./tools/run_tests.sh --integration-only
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'
          cache: true
      - name: Run tests
        run: WEAVIATE_VERSION=${WEAVIATE_VERSION} ./tools/run_tests.sh --unit-only
  tests-deprecated:
    runs-on: ubuntu-latest
    env:
      EXTERNAL_WEAVIATE_RUNNING: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'
          cache: true
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: ${{ !github.event.pull_request.head.repo.fork }}
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Run tests
        run: WEAVIATE_VERSION=${WEAVIATE_VERSION} ./tools/run_tests.sh --deprecated-only
